### ISSUE TITLE
[Editor.js] Path to image upload is missing parts

### ISSUE THREAD

**Issue by podcasthosting** [spatie/mailcoach-packages#1]
Using the editor.js integration in our Mailcoach is awesome except that the path to uploaded images is not correct.

The image upload itself works fine. The image is stored in the specified filesystem but the editor and a sent mail uses a wrong path.

We have a filesystem "public" like this:

        'public' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'url' => env('APP_URL').'/storage',
            'visibility' => 'public',
        ],

(Internally there is a symlink linking /public/storage to /storage/app/public).

The image link in the editor (and the mails) ends up being https://www.hostname.com/62/conversions/IMG_3184_1-image.jpg?v=1636458939 instead of the expected https://www.hostname.com/storage/62/conversions/IMG_3184_1-image.jpg?v=1636458939

**Comment by riasvdv** [comment]
What is your `APP_URL` set as?

**Comment by podcastdecontent** [comment]
It is set to the full domain including protocol: https://www.podcast.de

**Comment by podcastdecontent** [comment]
We found the issue. We had a custom MediaLibraryUrlGenerator class that was causing the issue. The issue can be closed.

**Comment by riasvdv** [comment]
Good to hear!
