### ISSUE TITLE
[Editor.js] BR tags aren't rendered for line breaks

### ISSUE THREAD

**Issue by sebastiandedeyne** [spatie/mailcoach-packages#2]

**Comment by riasvdv** [comment]
Can't seem to reproduce this one:

Editor.js:
![image](https://user-images.githubusercontent.com/3626559/149336450-e2abc621-2405-4441-9e68-ecc7ae3de560.png)

Preview:
![image](https://user-images.githubusercontent.com/3626559/149336510-b475351f-a330-4225-8852-bf977ae97cb4.png)

HTML:
![image](https://user-images.githubusercontent.com/3626559/149336577-597d0b03-c19b-413b-ab08-a9390c7992fc.png)
