### ISSUE TITLE
Replacements like ::subscriber.uuid:: do not work when used in URLs

### ISSUE THREAD

**Issue by JackWH** [spatie/mailcoach-packages#9]
**Describe the bug**
I'm trying to pass the Subscriber's UUID into a URL in my email, using `::subscriber.uuid::`. But when the Automation mail is sent out, the UUID is not being replaced. All other replacements are being made correctly. 

I'm using the EditorJS Mailcoach editor package and am trying to append the UUID to the end of a URL on a button. It seems [from here](https://github.com/spatie/laravel-mailcoach/issues/923) that the EditorJS implementation is causing this specifically.

I suspect (?) it's failing to replace as the URL parameters are being escaped *before* the replacements are made, so the `::` surroundings are being converted to `%3A%3Asubscriber.uuid%3A%3A`, preventing replacement.

This seems like a bug to me, as there are certainly times when we'd need to merge something into a URL contained in the message.

**Versions**
- spatie/laravel-mailcoach — `5.4.0`
- spatie/laravel-mailcoach-editor — `1.3.0`
- PHP — `8.1`
- Laravel — `9.5.1`

**To Reproduce**
1. Create an Automation mail
2. Include `::subscriber.uuid::` in a URL in the message
3. Trigger a send
4. The `::subscriber.uuid::` text will not be replaced.

**Expected behavior**
`::subscriber.uuid::` and other replacements should replace correctly in URLs.

**Comment by riasvdv** [comment]
This should be fixed already in one of the latest releases, forgot to close this
